### PR TITLE
:bug: [backend/eth] conclude after progression into final

### LINKED ISSUE #147: ensureConcluded fails when channel has been progressed to final
**Location:** backend/eth/conclude, contracts/Adjudicator.sol

**Problem:** When a channel has been force-update on-chain into a final state, the participants will not have fully signed states. Now, when calling `ensureConcluded`, it will call `concludeFinal`, which expects a fully-signed state and thus fails.

**Idea:** If a channel has been force-updated into final, the client should call `conclude` instead of `concludeFinal`, because `conclude` does not require signatures. The client must be able to detect whether a channel is in a final state on-chain. Usually, we indicate that by setting `phase = CONCLUDED`. Hence, I suggest that we change the contract such that if a state is force-updated to final, we automatically set `phase = CONCLUDED`.

Update: We can also apply a quick fix that doesn't require a change in the contracts. We can check whether the current on-chain phase is `FORCE_EXECUTION`. If this is the case, we know that the state resulted from force execution, which means we do not have the all signatures and need to call `conclude` instead of `concludeFinal`.

### PR DESCRIPTION
**Pull request by matthiasgeihs**
Closes #147

### CODE REVIEW

File: backend/ethereum/channel/conclude.go [hunk 1]
```diff
@@ -119,6 +133,30 @@ func (a *Adjudicator) isConcluded(ctx context.Context, sub *subscription.EventSu
...
+	defer sub.Close()
+	events := make(chan *subscription.Event, 10)
+	subErr := make(chan error, 1)
+	// Write the events into events.
+	go func() {
+		defer close(events)
+		subErr <- sub.ReadPast(ctx, events)
+	}()
+	// Read all events and check for force execution.
+	for _e := range events {
```
Comment (ggwpez) [inline backend/ethereum/channel/conclude.go:151]: Looking at this manual filter logic really make me want implement #102 :laughing:

File: backend/ethereum/channel/conclude.go [hunk 2]
```diff
@@ -119,6 +133,30 @@ func (a *Adjudicator) isConcluded(ctx context.Context, sub *subscription.EventSu
...
+	if err != nil {
+		return false, errors.WithMessage(err, "subscribing")
+	}
+	defer sub.Close()
+	events := make(chan *subscription.Event, 10)
+	subErr := make(chan error, 1)
+	// Write the events into events.
+	go func() {
+		defer close(events)
+		subErr <- sub.ReadPast(ctx, events)
```
Comment (ggwpez) [inline backend/ethereum/channel/conclude.go:148]: I think in theory this would need a sub-ctx as context, to ensure that it gets cancelled on function exit.  
In practice there will probably not be enough events anyway.

File: backend/ethereum/channel/conclude.go [hunk 3]
```diff
@@ -119,6 +133,30 @@ func (a *Adjudicator) isConcluded(ctx context.Context, sub *subscription.EventSu
...
+	}()
+	// Read all events and check for force execution.
+	for _e := range events {
+		e := _e.Data.(*adjudicator.AdjudicatorChannelUpdate)
+		if e.Phase == phaseForceExec {
```
Comment (ggwpez) [inline backend/ethereum/channel/conclude.go:153]: Does it matter that you do not check all events? Can something after the force-exec happen?

File: backend/ethereum/channel/conclude.go [hunk 4]
```diff
@@ -100,6 +95,25 @@ func (a *Adjudicator) ensureConcluded(ctx context.Context, req channel.Adjudicat
...
+		return errors.WithMessage(err, "checking force execution")
+	}
+	if req.Tx.IsFinal && !forceExecuted {
+		err = errors.WithMessage(a.callConcludeFinal(ctx, req), "calling concludeFinal")
+	} else {
+		err = errors.WithMessage(a.callConclude(ctx, req, subStates), "calling conclude")
+	}
+	if IsErrTxFailed(err) {
+		a.log.Warn("Calling conclude(Final) failed, waiting for event anyways...")
+	} else if err != nil {
```
Comment (ggwpez) [inline backend/ethereum/channel/conclude.go:111]: I dont think you need this _else if_.

File: backend/ethereum/channel/conclude.go [hunk 5]
```diff
@@ -100,6 +95,25 @@ func (a *Adjudicator) ensureConcluded(ctx context.Context, req channel.Adjudicat
...
+	if err != nil {
+		return errors.WithMessage(err, "checking force execution")
+	}
+	if req.Tx.IsFinal && !forceExecuted {
+		err = errors.WithMessage(a.callConcludeFinal(ctx, req), "calling concludeFinal")
+	} else {
+		err = errors.WithMessage(a.callConclude(ctx, req, subStates), "calling conclude")
+	}
+	if IsErrTxFailed(err) {
+		a.log.Warn("Calling conclude(Final) failed, waiting for event anyways...")
```
Comment (ggwpez) [inline backend/ethereum/channel/conclude.go:110]: Please log the error, since it is also not returned.

**Review by ggwpez — CHANGES_REQUESTED** [review]
Only one change request, others are comments.

File: backend/ethereum/channel/conclude.go (hunk 5 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/conclude.go:110]: This was not changed, just moved, but I will consider logging the error.

File: backend/ethereum/channel/conclude.go (hunk 4 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/conclude.go:111]: we do, because we don't want to fail, if it's an `ErrTxFailed`.

File: backend/ethereum/channel/conclude.go (hunk 2 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/conclude.go:148]: ok, let's use a sub-context then.

File: backend/ethereum/channel/conclude.go (hunk 1 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/conclude.go:151]: feel free :)

File: backend/ethereum/channel/conclude.go (hunk 3 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/conclude.go:153]: Currently, the only phase after FORCE_EXEC is CONCLUDED. Anyhow, it's a good observation. I will make sure that I check the phase of the last event, because this was the intention.

**Comment by matthiasgeihs** [comment]
@ggwpez  Addressed your comments, please have another look.

**Review by ggwpez — COMMENTED** [review]
Looks good! I assume you still squash.

**Comment by matthiasgeihs** [comment]
Rebased, please check and merge.

**Review by ggwpez — APPROVED** [review]
