### PR TITLE
Fix tx nonce mismatch error: approach 1

### LINKED ISSUE #62: ERC20 Depositor nonce race
**Problem**: The `ERC20Depositor` sends two transactions (increase allowance and deposit) in the same block.  
This seems to be causing issues with how the nonce is determined. Sometimes its transactions revert.

**Possible solutions**:  
1. Manually increasing the nonce by one after the first TX
2. Wait for the first TX to be mined (which is actually the job of the `Funder`)
3. Poll the nonce multiple times until a new one is returned

I opt for `1.` as it seems the easiest and fastest.

### PR DESCRIPTION
**Pull request by manoranjith**
Fix is attempted using approach 1 suggested in #62.

### CODE REVIEW

**Comment by matthiasgeihs** [comment]
LGTM, but there is a typo in your sign off.

**Comment by manoranjith** [comment]
Fixed the signed-off message.

File: backend/ethereum/channel/contractbackend.go [hunk 1]
```diff
@@ -130,6 +143,17 @@ func (c *ContractBackend) NewTransactor(ctx context.Context, gasLimit uint64,
 	auth.GasLimit = gasLimit
 	auth.Context = ctx
 
+	nonce, err := c.PendingNonceAt(ctx, acc.Address)
+	if err != nil {
+		return nil, errors.Wrap(err, "fetching nonce")
```
Comment (ggwpez) [inline backend/ethereum/channel/contractbackend.go:148]: I think you have to check for `IsChainNotReachableError` here.

File: backend/ethereum/channel/contractbackend.go [hunk 2]
```diff
@@ -122,6 +128,13 @@ func (c *ContractBackend) pastOffsetBlockNum(ctx context.Context) (uint64, error
 // set the value manually afterwards if it should be different from 0.
 func (c *ContractBackend) NewTransactor(ctx context.Context, gasLimit uint64,
 	acc accounts.Account) (*bind.TransactOpts, error) {
+	c.nonceMtx.Lock()
+	defer c.nonceMtx.Unlock()
+	expectedNextNonce, found := c.expectedNextNonce[acc.Address]
```
Comment (ggwpez) [inline backend/ethereum/channel/contractbackend.go:133]: You use the `expectedNextNonce` value below. Does golang define how it is set if the map access fails?

**Review by ggwpez — CHANGES_REQUESTED** [review]

File: backend/ethereum/channel/contractbackend.go (hunk 1 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/contractbackend.go:148]: Why?

File: backend/ethereum/channel/contractbackend.go (hunk 2 above)
Comment (matthiasgeihs) [reply backend/ethereum/channel/contractbackend.go:133]: [Default zero value](https://golang.org/ref/spec#The_zero_value)

File: backend/ethereum/channel/contractbackend.go (hunk 1 above)
Comment (manoranjith) [reply backend/ethereum/channel/contractbackend.go]: @matthiasgeihs  Because, we explicitly inform the user by returning a named error when there are problems connecting with the blockchain node. 

@ggwpez I have fixed this now.

Comment (matthiasgeihs) [reply backend/ethereum/channel/contractbackend.go]: I see. It seems a bit unclean that we introduce such specific error handling logic in so many places. We could add wrappers for the handful of functions that need this handling and then consistently use the wrappers, right? It's ok here, but it's something worth discussing in general, I think.

Comment (ggwpez) [reply backend/ethereum/channel/contractbackend.go]: Yes the initial approach calls the error wrapping on the lowest level, where we also could have done it on the highest…  
Its much more effort like this i think.

File: backend/ethereum/channel/contractbackend.go (hunk 2 above)
Comment (ggwpez) [reply backend/ethereum/channel/contractbackend.go:133]: Good to know.

**Review by ggwpez — APPROVED** [review]
